### ISSUE TITLE
stop action: "40: [: unexpected operator"

### ISSUE THREAD

**Issue by stapelberg** [akhilvij/systemd-to-sysvinit-converter#6]
Your generated scripts contain a line like this:

```
        if [ "$1" == "stop" ]; then
                exit 0
        fi
```

This is wrong. In shell scripts, the operator to check for string equality is `=`, not `==`:

```
        if [ "$1" = "stop" ]; then
                exit 0
        fi
```

**Comment by akhilvij** [comment]
We're testing the script in bash, so couldn't catch the error. Thank you for pointing it out.

**Comment by stapelberg** [comment]
There’s `checkbashisms` for catching bash-specific things. Also, you should really test it with dash, too, since that’s the default `/bin/sh` nowadays.

**Comment by akhilvij** [comment]
Thanks for the tips. They'll be of great help.

**Comment by daxaxelrod** [comment]
Just want to say thank you, 11 years later.
